### ISSUE TITLE
Unable to install from pkg.gpud.dev

### ISSUE THREAD

**Issue by chatter92** [leptonai/gpud#102]
When I try to install following the instructions in README, I get the following:

```
sh-4.2$ curl -fsSL https://pkg.gpud.dev/install.sh | sh
curl: (22) The requested URL returned error: 404
```
It errors out here: https://github.com/leptonai/gpud/blob/main/install.sh#L119

**Comment by gyuho** [comment]
@chatter92 Could you manually run the commands in https://github.com/leptonai/gpud/blob/main/install.sh#L119, and share your environments? 

I am suspecting it tried to install the old version and in amazon linux (which is only supported after >=0.0.4).

**Comment by gyuho** [comment]
@chatter92 Can you also try the script in https://github.com/leptonai/gpud/pull/105? I would like to know what URL it was trying to download from. Thanks.

**Comment by gyuho** [comment]
Please try https://github.com/leptonai/gpud/releases/tag/v0.0.5 and let us know if it still breaks.
