### ISSUE TITLE
Interesting segfault from my experiment

### ISSUE THREAD

**Issue by Yangqing** [leptonai/gpud#11]
This happens on my local box with the consumer grade Titan V GPU. GPUD works perfectly on it.

I wanted to simulate a GPU failure, so I did an nvidia-smi trick to drain the GPU card and make it invisible:

```
(base) ➜  sudo nvidia-smi -i 01:00.0 -pm 0
Disabled persistence mode for GPU 00000000:01:00.0.
All done.
(base) ➜  sudo nvidia-smi drain -p 0000:01:00.0 -m 1
Successfully set GPU 00000000:01:00.0 drain state to: draining.
(base) ➜  nvidia-smi                      
No devices were found
```

After that, I tried to use gpud to check the health of the machine and it gave me a segfault:
```
(base) ➜  code gpud scan  
⌛ scanning the host
⌛ scanning nvidia accelerators
✘ nvidia-smi check failed with 1 error(s)
exit status 6
✔ successfully checked fabric manager
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc40405]

goroutine 1 [running]:
github.com/leptonai/gpud/components/accelerator/nvidia/query.(*Output).PrintInfo(0xc0004f6640, 0x0)
        /root/goWork/src/github.com/leptonai/gpud/components/accelerator/nvidia/query/query.go:329 +0x445
github.com/leptonai/gpud/components/diagnose.Scan({0x19829c8, 0xc00038e0e0}, 0x1388, 0x0)
        /root/goWork/src/github.com/leptonai/gpud/components/diagnose/scan.go:46 +0x225
github.com/leptonai/gpud/cmd/gpud/command.cmdScan(0xc000218160?)
        /root/goWork/src/github.com/leptonai/gpud/cmd/gpud/command/scan.go:15 +0x65
github.com/urfave/cli.HandleAction({0x14c64e0?, 0x17f8a10?}, 0x4?)
        /root/goWork/src/github.com/leptonai/gpud/vendor/github.com/urfave/cli/app.go:524 +0x50
github.com/urfave/cli.Command.Run({{0x1700a32, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x174ab89, 0x29}, {0x0, ...}, ...}, ...)        /root/goWork/src/github.com/leptonai/gpud/vendor/github.com/urfave/cli/command.go:175 +0x67c
github.com/urfave/cli.(*App).Run(0xc0005041c0, {0xc000040060, 0x2, 0x2})
        /root/goWork/src/github.com/leptonai/gpud/vendor/github.com/urfave/cli/app.go:277 +0xb3b
main.main()
        /root/goWork/src/github.com/leptonai/gpud/cmd/gpud/main.go:12 +0x2d
```

I think we should probably grab the situation - "GPU is gone" or "there is no GPU" - and just choose one of two paths to report:
- "(if possible) hey, there used to be a gpu, and now the gpu is gone, so there is an issue."
- "hey, nvidia-smi reports that there are no gpus, so I won't check gpu status, but I consider this a fine state."

**Comment by Yangqing** [comment]
![image](https://github.com/user-attachments/assets/14d31bbf-2502-43a9-bbd9-e44d5f1354c0)

Also, interestingly, in the current state, the platform will display that the machine is online, but no information can be obtained. The health info also shows nothing. (Possibly because gpud quits half way?)

![image](https://github.com/user-attachments/assets/ed69de8c-e8a8-41a6-8eac-30b667d7cdfd)

**Comment by gyuho** [comment]
Fixed in https://github.com/leptonai/gpud/pull/4. We will release a new version soon!

**Comment by gyuho** [comment]
https://github.com/leptonai/gpud/releases/tag/v0.0.1-alpha2 has been released.

And https://github.com/leptonai/gpud?tab=readme-ov-file#installation

> curl -fsSL https://pkg.gpud.dev/install.sh | sh

now points to the `v0.0.1-alpha2`.
