### ISSUE TITLE
can't get gpu info with wsl platform

### ISSUE THREAD

**Issue by zhuima** [leptonai/gpud#203]
**ENV**
1. os: Ubuntu 22.04.4 LTS in  5.15.167.4-microsoft-standard-WSL2
2. gpud: gpud version v0.2.3

**exec gpud scan:**

```
admin@test$ sudo gpud scan


⌛ scanning the host

⌛ scanning the process counts
✔ counted processes by status
✔ "sleep" 65
✔ "running" 1

⌛ scanning dmesg for 5000 lines
✔ scanned dmesg file -- found no issue

⌛ checking network connectivity to edge/derp servers

✔ latency check complete



✔ scan complete
```

**Comment by gyuho** [comment]
Hello, can you share the `nvidia-smi` output?

**Comment by zhuima** [comment]
![image](https://github.com/user-attachments/assets/b484ef4d-18cf-4932-854a-b98a9d113de6)

**Comment by zhuima** [comment]
ui page also can't get gpu info
![image](https://github.com/user-attachments/assets/5889e619-49e4-4f51-b484-0f30224231ab)

**Comment by gyuho** [comment]
@zhuima We are adding more debugging level logs to root cause this. We will let you know once the new release is out.

**Comment by zhuima** [comment]
I'll test out the latest version

**Comment by gyuho** [comment]
Also, could you share the output of

> lspci | grep -i nvidia

**Comment by zhuima** [comment]
![image](https://github.com/user-attachments/assets/eda2a158-d2d7-4c61-8e92-a443243699c8)
nothing output

**Comment by gyuho** [comment]
https://github.com/leptonai/gpud/releases/tag/v0.2.4 now has `gpud scan --log-level=debug` flag. Could you try that to double confirm

**Comment by gyuho** [comment]
Me and @photoszzt did some search and found out https://github.com/microsoft/WSL/issues/9821 -- quiet a different platform: https://docs.nvidia.com/cuda/wsl-user-guide/index.html#cuda-support-for-wsl-2

I don't think we will full support WSL platform for now.  Please try with Linux.

**Comment by zhuima** [comment]
thanks
