### ISSUE TITLE
Installation on Ubuntu 20.04.6 LTS `GLIBC_2.33' not found

### ISSUE THREAD

**Issue by eicca** [leptonai/gpud#31]
Hello there,

Thanks a lot for this wonderful piece of software!

I managed to install gpud on Ubuntu 24.04, however, while installing on 20.04.6 I'm getting the following error:

```
./gpud: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./gpud)
./gpud: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by ./gpud)
./gpud: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./gpud)
```

My GLIBC version:
```
ldd --version
ldd (Ubuntu GLIBC 2.31-0ubuntu9.16) 2.31
```

Unfortunately, it's a pre-configured image, so I can't upgrade ubuntu. 

Is there a way to get it working except complying gpud myself for my version of glibc?

Thanks a lot in advance and thanks for open sourcing it!

**Comment by gyuho** [comment]
@eicca Thanks for the report!

Could you try the Ubuntu 20.04 build binary from this release page? https://github.com/leptonai/gpud/releases/tag/v0.0.1-alpha5

**Comment by gyuho** [comment]
Also

> I managed to install gpud on Ubuntu 24.04

So, it worked on ubuntu 24.04, but the same binary did not work on 22.04? And which version/binary you used will be helpful :)

**Comment by eicca** [comment]
> @eicca Thanks for the report!
> 
> Could you try the Ubuntu 20.04 build binary from this release page? https://github.com/leptonai/gpud/releases/tag/v0.0.1-alpha5

Thanks a lot for your reply! Downloading the binary for 20.04 directly worked!

For some reason the installer downloaded the binary for 22.04 :shrug:

**Comment by eicca** [comment]
> @eicca Do you also need Ubuntu 24.04 binary? Or does the binary for either 20.04 or 22.04 work on your 24.04?

The binary for 22.04 worked on my 24.04 without problems :ok: 

Thanks a lot for looking into this!

**Comment by seanxuu** [comment]
> Also
> 
> > I managed to install gpud on Ubuntu 24.04
> 
> So, it worked on ubuntu 24.04, but the same binary did not work on 22.04? And which version/binary you used will be helpful :)

Is that the only way to install gpud on ubuntu 20?

**Comment by gyuho** [comment]
@seanxuu Our latest release has Ubuntu 20.04 builds: https://github.com/leptonai/gpud/releases/tag/v0.0.1-alpha6

Could you try?

**Comment by Coldmooon** [comment]
> @seanxuu Our latest release has Ubuntu 20.04 builds: https://github.com/leptonai/gpud/releases/tag/v0.0.1-alpha6
> 
> Could you try?

I just tryied the v0.0.1-alpha6](https://github.com/leptonai/gpud/releases/tag/v0.0.1-alpha6). It worked on Ubuntu 20.04. But the install script in the README.MD does not work on Ubuntu 20.04, and will output `GLIBC_2.33' not found

**Comment by gyuho** [comment]
@Coldmooon Thanks for the report. Yes, we are making the fix the point our install script endpoint to the one that supports Ubuntu 20.04. Will keep you updated.

**Comment by gyuho** [comment]
@Coldmooon @seanxuu Please try again with the install script (our official one also updated).

And https://github.com/leptonai/gpud/releases/tag/v0.0.1-alpha7 has been released.
